// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InitialLoadState.
const (
	COMPLETED             InitialLoadState = "COMPLETED"
	LOADINGFROMAGRIROUTER InitialLoadState = "LOADING_FROM_AGRIROUTER"
	LOADINGTOAGRIROUTER   InitialLoadState = "LOADING_TO_AGRIROUTER"
	RECONCILING           InitialLoadState = "RECONCILING"
)

// Valid indicates whether the value is a known member of the InitialLoadState enum.
func (e InitialLoadState) Valid() bool {
	switch e {
	case COMPLETED:
		return true
	case LOADINGFROMAGRIROUTER:
		return true
	case LOADINGTOAGRIROUTER:
		return true
	case RECONCILING:
		return true
	default:
		return false
	}
}

// Defines values for PartyReferenceType.
const (
	PartyReferenceTypeOrganization PartyReferenceType = "organization"
	PartyReferenceTypePerson       PartyReferenceType = "person"
)

// Valid indicates whether the value is a known member of the PartyReferenceType enum.
func (e PartyReferenceType) Valid() bool {
	switch e {
	case PartyReferenceTypeOrganization:
		return true
	case PartyReferenceTypePerson:
		return true
	default:
		return false
	}
}

// Address defines model for Address.
type Address struct {
	City *string `json:"city,omitempty"`

	// Country ISO 3166-1 alpha-2 country code.
	Country    *string `json:"country,omitempty"`
	PoBox      *string `json:"poBox,omitempty"`
	PostalCode *string `json:"postalCode,omitempty"`
	State      *string `json:"state,omitempty"`
	Street     *string `json:"street,omitempty"`
}

// Contact defines model for Contact.
type Contact struct {
	Email  *openapi_types.Email `json:"email,omitempty"`
	Mobile *string              `json:"mobile,omitempty"`
	Phone  *string              `json:"phone,omitempty"`
}

// Entity Any master-data entity. Used only on the event stream, which carries every opted-in entity type over a single connection; the typed resources use the concrete schemas directly.
type Entity struct {
	union json.RawMessage
}

// EntityReference A reference to another entity by canonical and/or local id. On send either identifier suffices: a localId is resolved against the sender's own mapping, and is rejected if the target has not been sent yet. On delivery agrirouter populates agrirouterId, since the sender's localId does not resolve in the receiver's namespace.
type EntityReference struct {
	AgrirouterId *openapi_types.UUID `json:"agrirouterId,omitempty"`
	LocalId      *string             `json:"localId,omitempty"`
	union        json.RawMessage
}

// EntityReference0 defines model for EntityReference.0.
type EntityReference0 = interface{}

// EntityReference1 defines model for EntityReference.1.
type EntityReference1 = interface{}

// EntityRequest A lazy-loading request for a single canonical object.
type EntityRequest struct {
	// AgrirouterId The canonical identifier of the wanted entity.
	AgrirouterId openapi_types.UUID `json:"agrirouterId"`
}

// EntityTypeToggle defines model for EntityTypeToggle.
type EntityTypeToggle struct {
	// EntityType [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). The entity type this toggle applies to.
	//
	//
	// Examples: organizations, persons, farms, fields, field-boundaries
	EntityType string `json:"entityType"`
}

// Envelope Fields common to every master-data entity. The concrete entity type is determined by the path; each entity schema pins the `type` discriminator so that objects remain self-describing on the event stream.
type Envelope struct {
	Active *bool `json:"active,omitempty"`

	// AgrirouterId Canonical identifier, assigned by agrirouter. Absent on first send.
	AgrirouterId *openapi_types.UUID `json:"agrirouterId,omitempty"`

	// LocalId Always the *acting* endpoint's own identifier for the entity, in both directions: on send the sending endpoint's, on delivery the receiving endpoint's (named by `recipientEndpointId`). It never carries another endpoint's identifier, a sibling endpoint of the same application included. A local store is scoped to the endpoint, so the same string sent by two endpoints is two records.
	//
	// Required on send. On delivery it is present when agrirouter holds a mapping for the receiving endpoint, and absent when it does not — an object that endpoint has not bound, or has unbound. An absent `localId` means "you do not hold this object": create it locally and bind the identifier you issue, or — if you recognise it in a store you already share with another endpoint — bind without creating.
	LocalId    *string    `json:"localId,omitempty"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`

	// RecipientEndpointId On delivery, the endpoint this copy is rendered for: the endpoint whose `localId` the envelope and every reference in it carry. Assigned by agrirouter; a value sent by a participant is ignored.
	//
	// Because the identifier mapping is scoped to the endpoint, the event stream carries one frame per recipient endpoint rather than one per object. An application with two opted-in endpoints in one tenant receives the same canonical object twice, rendered for each, and partitions on this field. On a write response it is the endpoint named in `x-agrirouter-endpoint-id`.
	RecipientEndpointId *openapi_types.UUID `json:"recipientEndpointId,omitempty"`

	// Revision Monotonic per-object counter maintained by agrirouter. Never taken from the body: the revision a write was made from travels in the `x-agrirouter-base-revision` header, where it is compared and discarded.
	Revision *int `json:"revision,omitempty"`

	// SourceEndpointId The agrirouter identifier of the endpoint whose change produced this revision. It always belongs to `tenantId`.
	SourceEndpointId *openapi_types.UUID `json:"sourceEndpointId,omitempty"`

	// TenantId The tenant the object belongs to. Assigned by agrirouter; a value sent by a participant is ignored. On send the tenant follows from the endpoint named in `x-agrirouter-endpoint-id`.
	//
	// One application stream carries every tenant the application is routed to, so on delivery this is the field that says which of them an object belongs to. A receiver holding data for several tenants partitions on it rather than on the connection.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Farm A grouping of fields that the farmer considers part of the same management group.
type Farm struct {
	Active  *bool    `json:"active,omitempty"`
	Address *Address `json:"address,omitempty"`

	// AgrirouterId Canonical identifier, assigned by agrirouter. Absent on first send.
	AgrirouterId *openapi_types.UUID `json:"agrirouterId,omitempty"`

	// GeoReference A GeoJSON Point (longitude, latitude) locating the farm.
	GeoReference *Geometry `json:"geoReference,omitempty"`

	// LocalId Always the *acting* endpoint's own identifier for the entity, in both directions: on send the sending endpoint's, on delivery the receiving endpoint's (named by `recipientEndpointId`). It never carries another endpoint's identifier, a sibling endpoint of the same application included. A local store is scoped to the endpoint, so the same string sent by two endpoints is two records.
	//
	// Required on send. On delivery it is present when agrirouter holds a mapping for the receiving endpoint, and absent when it does not — an object that endpoint has not bound, or has unbound. An absent `localId` means "you do not hold this object": create it locally and bind the identifier you issue, or — if you recognise it in a store you already share with another endpoint — bind without creating.
	LocalId    *string    `json:"localId,omitempty"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	Name       string     `json:"name"`

	// Owner The organization or person that holds the farm.
	Owner PartyReference `json:"owner"`

	// Partners Parties holding a role on this farm, such as the contractor that works it or the advisor that reads it.
	Partners *[]Partner `json:"partners,omitempty"`

	// RecipientEndpointId On delivery, the endpoint this copy is rendered for: the endpoint whose `localId` the envelope and every reference in it carry. Assigned by agrirouter; a value sent by a participant is ignored.
	//
	// Because the identifier mapping is scoped to the endpoint, the event stream carries one frame per recipient endpoint rather than one per object. An application with two opted-in endpoints in one tenant receives the same canonical object twice, rendered for each, and partitions on this field. On a write response it is the endpoint named in `x-agrirouter-endpoint-id`.
	RecipientEndpointId *openapi_types.UUID `json:"recipientEndpointId,omitempty"`

	// Revision Monotonic per-object counter maintained by agrirouter. Never taken from the body: the revision a write was made from travels in the `x-agrirouter-base-revision` header, where it is compared and discarded.
	Revision *int `json:"revision,omitempty"`

	// SourceEndpointId The agrirouter identifier of the endpoint whose change produced this revision. It always belongs to `tenantId`.
	SourceEndpointId *openapi_types.UUID `json:"sourceEndpointId,omitempty"`

	// SpecialisedUsageType Production orientation of the farm (e.g. arable farming, dairy, vineyard, orchard). Free-form, drawn from AGROVOC where a matching concept exists.
	SpecialisedUsageType *string `json:"specialisedUsageType,omitempty"`

	// TenantId The tenant the object belongs to. Assigned by agrirouter; a value sent by a participant is ignored. On send the tenant follows from the endpoint named in `x-agrirouter-endpoint-id`.
	//
	// One application stream carries every tenant the application is routed to, so on delivery this is the field that says which of them an object belongs to. A receiver holding data for several tenants partitions on it rather than on the connection.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`

	// Type Discriminator, set by agrirouter. Implied by the path on send.
	Type interface{} `json:"type,omitempty"`
}

// Field A named physical space where production agriculture takes place, used to partition and identify data.
type Field struct {
	Active *bool `json:"active,omitempty"`

	// AgrirouterId Canonical identifier, assigned by agrirouter. Absent on first send.
	AgrirouterId *openapi_types.UUID `json:"agrirouterId,omitempty"`

	// Area Nominal area in square metres.
	Area *float32 `json:"area,omitempty"`

	// Farm The farm this field belongs to.
	Farm *EntityReference `json:"farm,omitempty"`

	// FieldBoundaries References to the field's boundaries.
	FieldBoundaries *[]EntityReference `json:"fieldBoundaries,omitempty"`

	// HarvestPeriod Canonical harvest period as an interval. A discrete year is mapped to an interval on send; `label` may round-trip the native presentation.
	HarvestPeriod *HarvestPeriod `json:"harvestPeriod,omitempty"`

	// LocalId Always the *acting* endpoint's own identifier for the entity, in both directions: on send the sending endpoint's, on delivery the receiving endpoint's (named by `recipientEndpointId`). It never carries another endpoint's identifier, a sibling endpoint of the same application included. A local store is scoped to the endpoint, so the same string sent by two endpoints is two records.
	//
	// Required on send. On delivery it is present when agrirouter holds a mapping for the receiving endpoint, and absent when it does not — an object that endpoint has not bound, or has unbound. An absent `localId` means "you do not hold this object": create it locally and bind the identifier you issue, or — if you recognise it in a store you already share with another endpoint — bind without creating.
	LocalId *string `json:"localId,omitempty"`

	// Metadata Additional key/value metadata. Participants MUST preserve and relay metadata they do not understand.
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	ModifiedAt *time.Time              `json:"modifiedAt,omitempty"`
	Name       string                  `json:"name"`

	// Owner The organization or person holding this field, for systems that attribute fields to a party directly. When absent, the field is held by its farm's owner. When present, it takes precedence for this field, which is how a field held by one party but managed under another's farm is expressed.
	Owner *PartyReference `json:"owner,omitempty"`

	// RecipientEndpointId On delivery, the endpoint this copy is rendered for: the endpoint whose `localId` the envelope and every reference in it carry. Assigned by agrirouter; a value sent by a participant is ignored.
	//
	// Because the identifier mapping is scoped to the endpoint, the event stream carries one frame per recipient endpoint rather than one per object. An application with two opted-in endpoints in one tenant receives the same canonical object twice, rendered for each, and partitions on this field. On a write response it is the endpoint named in `x-agrirouter-endpoint-id`.
	RecipientEndpointId *openapi_types.UUID `json:"recipientEndpointId,omitempty"`

	// Revision Monotonic per-object counter maintained by agrirouter. Never taken from the body: the revision a write was made from travels in the `x-agrirouter-base-revision` header, where it is compared and discarded.
	Revision *int `json:"revision,omitempty"`

	// Soil Soil characteristics of a field.
	Soil *SoilInfo `json:"soil,omitempty"`

	// SourceEndpointId The agrirouter identifier of the endpoint whose change produced this revision. It always belongs to `tenantId`.
	SourceEndpointId *openapi_types.UUID `json:"sourceEndpointId,omitempty"`

	// TenantId The tenant the object belongs to. Assigned by agrirouter; a value sent by a participant is ignored. On send the tenant follows from the endpoint named in `x-agrirouter-endpoint-id`.
	//
	// One application stream carries every tenant the application is routed to, so on delivery this is the field that says which of them an object belongs to. A receiver holding data for several tenants partitions on it rather than on the connection.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`

	// Topography Slope / gradient, e.g. 7 (degrees).
	Topography *float32 `json:"topography,omitempty"`

	// Type Discriminator, set by agrirouter. Implied by the path on send.
	Type interface{} `json:"type,omitempty"`
}

// FieldBoundary A geometry identifying the geo-spatial coordinates of a field, including its outer boundary and any obstacles left out. A field may have several boundaries that differ in geometry by intended use.
type FieldBoundary struct {
	Active *bool `json:"active,omitempty"`

	// AgrirouterId Canonical identifier, assigned by agrirouter. Absent on first send.
	AgrirouterId *openapi_types.UUID `json:"agrirouterId,omitempty"`

	// Boundary A GeoJSON Polygon or MultiPolygon.
	Boundary Geometry `json:"boundary"`

	// BoundaryType [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). The boundary classification.
	//
	//
	// Examples: CONCEPTUAL, OPERATIONAL, ECONOMIC_DEFINED, ADMINISTRATIVE_RECEIVED
	BoundaryType *string `json:"boundaryType,omitempty"`

	// CreationMethod [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). How the boundary was produced.
	//
	//
	// Examples: UNKNOWN, MANUAL, DRIVEN, SURVEYED, AUTO_OPERATION, AUTO_IMAGERY, ADMINISTRATIVE
	CreationMethod *string `json:"creationMethod,omitempty"`

	// HarvestPeriod Canonical harvest period as an interval. A discrete year is mapped to an interval on send; `label` may round-trip the native presentation.
	HarvestPeriod *HarvestPeriod `json:"harvestPeriod,omitempty"`

	// LocalId Always the *acting* endpoint's own identifier for the entity, in both directions: on send the sending endpoint's, on delivery the receiving endpoint's (named by `recipientEndpointId`). It never carries another endpoint's identifier, a sibling endpoint of the same application included. A local store is scoped to the endpoint, so the same string sent by two endpoints is two records.
	//
	// Required on send. On delivery it is present when agrirouter holds a mapping for the receiving endpoint, and absent when it does not — an object that endpoint has not bound, or has unbound. An absent `localId` means "you do not hold this object": create it locally and bind the identifier you issue, or — if you recognise it in a store you already share with another endpoint — bind without creating.
	LocalId *string `json:"localId,omitempty"`

	// Metadata Additional key/value metadata. Participants MUST preserve and relay metadata they do not understand.
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	ModifiedAt *time.Time              `json:"modifiedAt,omitempty"`
	Obstacles  *[]Obstacle             `json:"obstacles,omitempty"`

	// RecipientEndpointId On delivery, the endpoint this copy is rendered for: the endpoint whose `localId` the envelope and every reference in it carry. Assigned by agrirouter; a value sent by a participant is ignored.
	//
	// Because the identifier mapping is scoped to the endpoint, the event stream carries one frame per recipient endpoint rather than one per object. An application with two opted-in endpoints in one tenant receives the same canonical object twice, rendered for each, and partitions on this field. On a write response it is the endpoint named in `x-agrirouter-endpoint-id`.
	RecipientEndpointId *openapi_types.UUID `json:"recipientEndpointId,omitempty"`

	// RegulatoryRequirements [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). A regulatory constraint applying to the boundary.
	//
	//
	// Examples: RED_ZONE_NITROGEN, WATER_PROTECTION_AREA
	RegulatoryRequirements *string `json:"regulatoryRequirements,omitempty"`

	// Revision Monotonic per-object counter maintained by agrirouter. Never taken from the body: the revision a write was made from travels in the `x-agrirouter-base-revision` header, where it is compared and discarded.
	Revision *int `json:"revision,omitempty"`

	// SourceEndpointId The agrirouter identifier of the endpoint whose change produced this revision. It always belongs to `tenantId`.
	SourceEndpointId *openapi_types.UUID `json:"sourceEndpointId,omitempty"`

	// TenantId The tenant the object belongs to. Assigned by agrirouter; a value sent by a participant is ignored. On send the tenant follows from the endpoint named in `x-agrirouter-endpoint-id`.
	//
	// One application stream carries every tenant the application is routed to, so on delivery this is the field that says which of them an object belongs to. A receiver holding data for several tenants partitions on it rather than on the connection.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`

	// Type Discriminator, set by agrirouter. Implied by the path on send.
	Type interface{} `json:"type,omitempty"`
}

// Geometry A GeoJSON geometry (RFC 7946). Positions are [longitude, latitude] and, optionally, altitude.
type Geometry struct {
	// Coordinates Nesting depth depends on `type`.
	Coordinates interface{} `json:"coordinates"`

	// Type [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). The GeoJSON geometry type.
	//
	//
	// Examples: Point, LineString, Polygon, MultiPolygon
	Type string `json:"type"`
}

// HarvestPeriod Canonical harvest period as an interval. A discrete year is mapped to an interval on send; `label` may round-trip the native presentation.
type HarvestPeriod struct {
	// Label Human-facing designation, e.g. "2026" or "2025/2026".
	Label     *string            `json:"label,omitempty"`
	ValidFrom openapi_types.Date `json:"validFrom"`

	// ValidTo Absent means open / current.
	ValidTo *openapi_types.Date `json:"validTo,omitempty"`
}

// IdMappingBinding One binding of a local identifier to a canonical object, as carried in bulk on the initial-load confirmation.
//
// Both ends belong to the calling application's own store: the object it matched, and what it calls that object. A mapping only ever travels from an application to agrirouter.
type IdMappingBinding struct {
	AgrirouterId openapi_types.UUID `json:"agrirouterId"`
	LocalId      string             `json:"localId"`
}

// IdMappingRejection A binding that could not be recorded: the pair as submitted, why, and the mapping standing in its way.
type IdMappingRejection struct {
	AgrirouterId openapi_types.UUID `json:"agrirouterId"`

	// ExistingMapping The mapping that already holds the taken identifier. Both of its ends belong to the rejected endpoint itself, so naming it discloses nothing the endpoint does not already hold, and it is what the endpoint shows the user resolving the conflict. Present for `LOCAL_ID_ALREADY_BOUND` and `AGRIROUTER_ID_ALREADY_BOUND`, absent for the other reasons, where no mapping is in the way.
	ExistingMapping *IdMappingBinding `json:"existingMapping,omitempty"`
	LocalId         string            `json:"localId"`

	// Reason [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). Why a binding could not be recorded.
	//
	// `LOCAL_ID_ALREADY_BOUND` — this endpoint already knows a different canonical object by that `localId`. `existingMapping` names it.
	//
	// `AGRIROUTER_ID_ALREADY_BOUND` — this endpoint already knows that canonical object by a different `localId`. `existingMapping` names it.
	//
	// `UNKNOWN_OBJECT` — no such canonical object, or the endpoint is not entitled to it. On the per-entity operation this is the `404` instead.
	//
	// `DUPLICATE_IN_REQUEST` — the same `localId` or the same `agrirouterId` appears in more than one pair of this request, which would make the outcome depend on the order pairs were applied in. Every pair involved is rejected and none is applied. Bulk path only.
	//
	//
	// Examples: LOCAL_ID_ALREADY_BOUND, AGRIROUTER_ID_ALREADY_BOUND, UNKNOWN_OBJECT, DUPLICATE_IN_REQUEST
	Reason IdMappingRejectionReason `json:"reason"`
}

// IdMappingRejectionReason [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). Why a binding could not be recorded.
//
// `LOCAL_ID_ALREADY_BOUND` — this endpoint already knows a different canonical object by that `localId`. `existingMapping` names it.
//
// `AGRIROUTER_ID_ALREADY_BOUND` — this endpoint already knows that canonical object by a different `localId`. `existingMapping` names it.
//
// `UNKNOWN_OBJECT` — no such canonical object, or the endpoint is not entitled to it. On the per-entity operation this is the `404` instead.
//
// `DUPLICATE_IN_REQUEST` — the same `localId` or the same `agrirouterId` appears in more than one pair of this request, which would make the outcome depend on the order pairs were applied in. Every pair involved is rejected and none is applied. Bulk path only.
//
// Examples: LOCAL_ID_ALREADY_BOUND, AGRIROUTER_ID_ALREADY_BOUND, UNKNOWN_OBJECT, DUPLICATE_IN_REQUEST
type IdMappingRejectionReason = string

// InitialLoadState Per-endpoint initial-load state, covering every entity type the endpoint is opted into.
//
// `LOADING_FROM_AGRIROUTER` — agrirouter is still sending the canonical set. Entered by opting the endpoint into its first entity type via the master-data configuration, and again whenever a further entity type is added there. Both are a user's opt-in decision carried out by agrirouter; a participant cannot enter this state directly, and an attempt to set it on the `status` resource is a `409`.
//
// `RECONCILING` — the whole canonical set has been delivered and the initial-load stream closed. agrirouter moves the endpoint here itself, and only this one, because it is the side that knows it has finished sending, which is also why this state is the authoritative answer to whether the set arrived: an endpoint cannot tell an orderly close from a dropped connection. The endpoint is now working through whatever conflicts reconciling surfaced, which may take as long as a user takes.
//
// `LOADING_TO_AGRIROUTER` — the endpoint has confirmed it reconciled, and is sending the objects it holds that the canonical set did not contain.
//
// `COMPLETED` — steady-state synchronization applies.
//
// The endpoint drives two of these transitions, both through the `status` resource: `RECONCILING` → `LOADING_TO_AGRIROUTER` and `LOADING_TO_AGRIROUTER` → `COMPLETED`.
type InitialLoadState string

// InitialLoadStateUpdate The target initial-load `state` for the endpoint. The states are accepted in order, and repeating the one the endpoint is already in is accepted too. `LOADING_FROM_AGRIROUTER` is never a transition an endpoint may make, from any state including from itself.
type InitialLoadStateUpdate struct {
	// IdMappings The bindings reconciliation produced: one entry per canonical object the endpoint matched to something it already held. Carried here because matching happens over a whole set, and the semantics are those of the per-entity `id-mapping` operation applied to each pair. Meaningful only on the transition to `LOADING_TO_AGRIROUTER`, which is where reconciliation is asserted to be done, and on a repeat of that transition, where the pairs are applied again and the rejections recomputed. Pairs are applied independently: any that cannot be recorded — because an identifier is already bound, because the canonical object is unknown to the endpoint, or because the request names the same identifier twice — come back in `rejectedIdMappings` rather than failing the transition.
	IdMappings *[]IdMappingBinding `json:"idMappings,omitempty"`

	// State Per-endpoint initial-load state, covering every entity type the endpoint is opted into.
	//
	// `LOADING_FROM_AGRIROUTER` — agrirouter is still sending the canonical set. Entered by opting the endpoint into its first entity type via the master-data configuration, and again whenever a further entity type is added there. Both are a user's opt-in decision carried out by agrirouter; a participant cannot enter this state directly, and an attempt to set it on the `status` resource is a `409`.
	//
	// `RECONCILING` — the whole canonical set has been delivered and the initial-load stream closed. agrirouter moves the endpoint here itself, and only this one, because it is the side that knows it has finished sending, which is also why this state is the authoritative answer to whether the set arrived: an endpoint cannot tell an orderly close from a dropped connection. The endpoint is now working through whatever conflicts reconciling surfaced, which may take as long as a user takes.
	//
	// `LOADING_TO_AGRIROUTER` — the endpoint has confirmed it reconciled, and is sending the objects it holds that the canonical set did not contain.
	//
	// `COMPLETED` — steady-state synchronization applies.
	//
	// The endpoint drives two of these transitions, both through the `status` resource: `RECONCILING` → `LOADING_TO_AGRIROUTER` and `LOADING_TO_AGRIROUTER` → `COMPLETED`.
	State InitialLoadState `json:"state"`
}

// InitialLoadStatus The endpoint's initial-load state. One per endpoint, covering every entity type it is opted into; an endpoint opted into no entity type has no initial-load state.
type InitialLoadStatus struct {
	// AwaitingUser Whether the endpoint's own software is needing user action — a conflict, a missing required attribute, a granularity mismatch. Raised by the endpoint through the `user-attention` resource and cleared by agrirouter, on the two endpoint-driven transitions only: advancing to `LOADING_TO_AGRIROUTER` clears it, and so does advancing to `COMPLETED`. The step to `RECONCILING` does not, since that is agrirouter reporting it has finished sending and says nothing about whether the user has finished deciding. agrirouter renders the flag as "waiting for you in <app>", linking to the master-data resolution URI supplied for this endpoint.
	AwaitingUser *bool `json:"awaitingUser,omitempty"`

	// EndpointId The agrirouter identifier of the endpoint this resource belongs to. The path addresses it by the participant's own `externalEndpointId`.
	EndpointId *openapi_types.UUID `json:"endpointId,omitempty"`

	// PreviousLoadCompletedAt When this endpoint last reached `COMPLETED`, present only if it has. Its presence means the canonical set now arriving is a repeat load — the endpoint was a participant before and has returned, having been opted out, disconnected from the hub, opted into a further entity type, or having asked for the set again itself. The identifier mapping survived all of these, so the objects arrive carrying the endpoint's own `localId` and match rather than reconcile. An endpoint MUST NOT take the arrival of a canonical set as evidence of a first connection: without this check it creates local duplicates of data it already holds.
	PreviousLoadCompletedAt *time.Time `json:"previousLoadCompletedAt,omitempty"`

	// RejectedIdMappings Bindings supplied on this request that could not be recorded, each with its `reason` and, where one exists, the mapping that stands in its way. They do not fail the transition: one unresolvable pair should not block the load of a set. The endpoint resolves them as it resolves a `409` on the per-entity operation, and rebinds through that operation once it has. Recomputed on every request that carries `idMappings`, including a repeat of the transition, so a retry after a lost response reports the current outcome rather than the first.
	RejectedIdMappings *[]IdMappingRejection `json:"rejectedIdMappings,omitempty"`

	// State Per-endpoint initial-load state, covering every entity type the endpoint is opted into.
	//
	// `LOADING_FROM_AGRIROUTER` — agrirouter is still sending the canonical set. Entered by opting the endpoint into its first entity type via the master-data configuration, and again whenever a further entity type is added there. Both are a user's opt-in decision carried out by agrirouter; a participant cannot enter this state directly, and an attempt to set it on the `status` resource is a `409`.
	//
	// `RECONCILING` — the whole canonical set has been delivered and the initial-load stream closed. agrirouter moves the endpoint here itself, and only this one, because it is the side that knows it has finished sending, which is also why this state is the authoritative answer to whether the set arrived: an endpoint cannot tell an orderly close from a dropped connection. The endpoint is now working through whatever conflicts reconciling surfaced, which may take as long as a user takes.
	//
	// `LOADING_TO_AGRIROUTER` — the endpoint has confirmed it reconciled, and is sending the objects it holds that the canonical set did not contain.
	//
	// `COMPLETED` — steady-state synchronization applies.
	//
	// The endpoint drives two of these transitions, both through the `status` resource: `RECONCILING` → `LOADING_TO_AGRIROUTER` and `LOADING_TO_AGRIROUTER` → `COMPLETED`.
	State     InitialLoadState `json:"state"`
	UpdatedAt *time.Time       `json:"updatedAt,omitempty"`
}

// MappingConflictError The `409` of a binding: an `Error` carrying the rejection that caused it. The same shape the bulk path returns per pair, so an endpoint resolves a conflict identically whichever path raised it. As there, the outcome is carried by `rejection.reason`; the `message` of the `Error` is diagnostic and MUST NOT be branched on.
type MappingConflictError struct {
	Message string `json:"message"`

	// Rejection A binding that could not be recorded: the pair as submitted, why, and the mapping standing in its way.
	Rejection IdMappingRejection `json:"rejection"`
}

// MasterdataConfig Per-endpoint, per-entity opt-in for master-data exchange. Absence of a toggle for an entity type means the endpoint is not opted in for it.
type MasterdataConfig struct {
	// EndpointId The agrirouter identifier of the endpoint this resource belongs to. The path addresses it by the participant's own `externalEndpointId`.
	EndpointId *openapi_types.UUID `json:"endpointId,omitempty"`

	// Toggles The entity types the user opted this endpoint into, empty where it is opted into none — always present, never absent. Set by the user in agrirouter.
	Toggles []EntityTypeToggle `json:"toggles"`
}

// Membership A role held by a person in one organization.
type Membership struct {
	// MemberRole [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). A role drawn from the ADAPT Role data type.
	//
	//
	// Examples: UNKNOWN, AUTHORIZER, CROP_ADVISOR, CUSTOMER, CUSTOM_SERVICE_PROVIDER, DATA_SERVICES_PROVIDER, END_USER, FARM_MANAGER, FINANCIER, STATIONARY_ASSET_SUPPLIER, GOVERNMENT_AGENCY, GROWER, INPUT_SUPPLIER, INSURANCE_AGENT, IRRIGATION_MANAGER, LABORER, MARKET_ADVISOR, MARKET_PROVIDER, MOBILE_ASSET_SUPPLIER, OPERATOR, OWNER, TRANSPORTER
	MemberRole Role `json:"memberRole"`

	// OrganizationId The organization the person belongs to.
	OrganizationId EntityReference `json:"organizationId"`
}

// Obstacle A GeoJSON Feature describing an in-field obstacle whose geometry is a Point, LineString, or Polygon.
type Obstacle struct {
	// Geometry A GeoJSON geometry (RFC 7946). Positions are [longitude, latitude] and, optionally, altitude.
	Geometry   Geometry `json:"geometry"`
	Properties struct {
		// Kind Obstacle kind, e.g. "pole", "tree", "waterhole".
		Kind string `json:"kind"`
	} `json:"properties"`
	Type interface{} `json:"type"`
}

// Organization A legal entity that may hold land and to which persons may belong. It plays no fixed role: whether it acts as a contractor or as a client follows from the relations it stands in, not from an attribute.
type Organization struct {
	Active  *bool    `json:"active,omitempty"`
	Address *Address `json:"address,omitempty"`

	// AgrirouterId Canonical identifier, assigned by agrirouter. Absent on first send.
	AgrirouterId   *openapi_types.UUID `json:"agrirouterId,omitempty"`
	BillingAddress *Address            `json:"billingAddress,omitempty"`

	// CommercialRegistryNumber Identifier from the commercial register.
	CommercialRegistryNumber *string  `json:"commercialRegistryNumber,omitempty"`
	Contact                  *Contact `json:"contact,omitempty"`

	// LocalId Always the *acting* endpoint's own identifier for the entity, in both directions: on send the sending endpoint's, on delivery the receiving endpoint's (named by `recipientEndpointId`). It never carries another endpoint's identifier, a sibling endpoint of the same application included. A local store is scoped to the endpoint, so the same string sent by two endpoints is two records.
	//
	// Required on send. On delivery it is present when agrirouter holds a mapping for the receiving endpoint, and absent when it does not — an object that endpoint has not bound, or has unbound. An absent `localId` means "you do not hold this object": create it locally and bind the identifier you issue, or — if you recognise it in a store you already share with another endpoint — bind without creating.
	LocalId    *string    `json:"localId,omitempty"`
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
	Name       string     `json:"name"`

	// RecipientEndpointId On delivery, the endpoint this copy is rendered for: the endpoint whose `localId` the envelope and every reference in it carry. Assigned by agrirouter; a value sent by a participant is ignored.
	//
	// Because the identifier mapping is scoped to the endpoint, the event stream carries one frame per recipient endpoint rather than one per object. An application with two opted-in endpoints in one tenant receives the same canonical object twice, rendered for each, and partitions on this field. On a write response it is the endpoint named in `x-agrirouter-endpoint-id`.
	RecipientEndpointId *openapi_types.UUID `json:"recipientEndpointId,omitempty"`

	// Revision Monotonic per-object counter maintained by agrirouter. Never taken from the body: the revision a write was made from travels in the `x-agrirouter-base-revision` header, where it is compared and discarded.
	Revision *int `json:"revision,omitempty"`

	// SourceEndpointId The agrirouter identifier of the endpoint whose change produced this revision. It always belongs to `tenantId`.
	SourceEndpointId *openapi_types.UUID `json:"sourceEndpointId,omitempty"`

	// TaxId Numerical identifier assigned by tax authorities.
	TaxId *string `json:"taxId,omitempty"`

	// TaxNumber Identifier assigned by tax authorities.
	TaxNumber *string `json:"taxNumber,omitempty"`

	// TenantId The tenant the object belongs to. Assigned by agrirouter; a value sent by a participant is ignored. On send the tenant follows from the endpoint named in `x-agrirouter-endpoint-id`.
	//
	// One application stream carries every tenant the application is routed to, so on delivery this is the field that says which of them an object belongs to. A receiver holding data for several tenants partitions on it rather than on the connection.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`

	// TradeId Numerical identifier assigned by public authorities.
	TradeId *string `json:"tradeId,omitempty"`

	// Type Discriminator, set by agrirouter. Implied by the path on send.
	Type interface{} `json:"type,omitempty"`
}

// Partner A party holding a role on a farm — the contractor that works it, the advisor that reads it. Records a business relationship only. It does NOT grant visibility of the farm: what an endpoint receives is decided by opt-in and routing.
type Partner struct {
	// PartnerId The organization or person acting as partner.
	PartnerId PartyReference `json:"partnerId"`

	// PartnerRole [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). A role drawn from the ADAPT Role data type.
	//
	//
	// Examples: UNKNOWN, AUTHORIZER, CROP_ADVISOR, CUSTOMER, CUSTOM_SERVICE_PROVIDER, DATA_SERVICES_PROVIDER, END_USER, FARM_MANAGER, FINANCIER, STATIONARY_ASSET_SUPPLIER, GOVERNMENT_AGENCY, GROWER, INPUT_SUPPLIER, INSURANCE_AGENT, IRRIGATION_MANAGER, LABORER, MARKET_ADVISOR, MARKET_PROVIDER, MOBILE_ASSET_SUPPLIER, OPERATOR, OWNER, TRANSPORTER
	PartnerRole Role `json:"partnerRole"`
}

// Party Attributes common to every party, whether an organization or a natural person. A farmer carries the fiscal identifiers as much as a company does; only the commercial register entry is specific to organizations.
type Party struct {
	Address        *Address `json:"address,omitempty"`
	BillingAddress *Address `json:"billingAddress,omitempty"`
	Contact        *Contact `json:"contact,omitempty"`

	// TaxId Numerical identifier assigned by tax authorities.
	TaxId *string `json:"taxId,omitempty"`

	// TaxNumber Identifier assigned by tax authorities.
	TaxNumber *string `json:"taxNumber,omitempty"`

	// TradeId Numerical identifier assigned by public authorities.
	TradeId *string `json:"tradeId,omitempty"`
}

// PartyReference A reference to a party. The slot admits both organizations and persons, so the entity type is required: a receiver that does not hold the target must lazy-load it, and the request endpoints are per entity type. Typed slots such as a field's farm need no discriminator.
type PartyReference struct {
	AgrirouterId *openapi_types.UUID `json:"agrirouterId,omitempty"`
	LocalId      *string             `json:"localId,omitempty"`
	Type         PartyReferenceType  `json:"type"`
	union        json.RawMessage
}

// PartyReferenceType defines model for PartyReference.Type.
type PartyReferenceType string

// PartyReference0 defines model for PartyReference.0.
type PartyReference0 = interface{}

// PartyReference1 defines model for PartyReference.1.
type PartyReference1 = interface{}

// Person A natural person. A person may hold land, and may belong to one or more organizations through `memberships`.
type Person struct {
	Active  *bool    `json:"active,omitempty"`
	Address *Address `json:"address,omitempty"`

	// AgrirouterId Canonical identifier, assigned by agrirouter. Absent on first send.
	AgrirouterId   *openapi_types.UUID `json:"agrirouterId,omitempty"`
	BillingAddress *Address            `json:"billingAddress,omitempty"`
	Contact        *Contact            `json:"contact,omitempty"`
	FirstName      *string             `json:"firstName,omitempty"`
	LastName       string              `json:"lastName"`

	// LocalId Always the *acting* endpoint's own identifier for the entity, in both directions: on send the sending endpoint's, on delivery the receiving endpoint's (named by `recipientEndpointId`). It never carries another endpoint's identifier, a sibling endpoint of the same application included. A local store is scoped to the endpoint, so the same string sent by two endpoints is two records.
	//
	// Required on send. On delivery it is present when agrirouter holds a mapping for the receiving endpoint, and absent when it does not — an object that endpoint has not bound, or has unbound. An absent `localId` means "you do not hold this object": create it locally and bind the identifier you issue, or — if you recognise it in a store you already share with another endpoint — bind without creating.
	LocalId *string `json:"localId,omitempty"`

	// Memberships The organizations this person belongs to, each with the role held there. A person carrying at least one entry is a member.
	Memberships *[]Membership `json:"memberships,omitempty"`
	ModifiedAt  *time.Time    `json:"modifiedAt,omitempty"`

	// RecipientEndpointId On delivery, the endpoint this copy is rendered for: the endpoint whose `localId` the envelope and every reference in it carry. Assigned by agrirouter; a value sent by a participant is ignored.
	//
	// Because the identifier mapping is scoped to the endpoint, the event stream carries one frame per recipient endpoint rather than one per object. An application with two opted-in endpoints in one tenant receives the same canonical object twice, rendered for each, and partitions on this field. On a write response it is the endpoint named in `x-agrirouter-endpoint-id`.
	RecipientEndpointId *openapi_types.UUID `json:"recipientEndpointId,omitempty"`

	// Revision Monotonic per-object counter maintained by agrirouter. Never taken from the body: the revision a write was made from travels in the `x-agrirouter-base-revision` header, where it is compared and discarded.
	Revision *int `json:"revision,omitempty"`

	// SourceEndpointId The agrirouter identifier of the endpoint whose change produced this revision. It always belongs to `tenantId`.
	SourceEndpointId *openapi_types.UUID `json:"sourceEndpointId,omitempty"`

	// TaxId Numerical identifier assigned by tax authorities.
	TaxId *string `json:"taxId,omitempty"`

	// TaxNumber Identifier assigned by tax authorities.
	TaxNumber *string `json:"taxNumber,omitempty"`

	// TenantId The tenant the object belongs to. Assigned by agrirouter; a value sent by a participant is ignored. On send the tenant follows from the endpoint named in `x-agrirouter-endpoint-id`.
	//
	// One application stream carries every tenant the application is routed to, so on delivery this is the field that says which of them an object belongs to. A receiver holding data for several tenants partitions on it rather than on the connection.
	TenantId *openapi_types.UUID `json:"tenantId,omitempty"`
	Title    *string             `json:"title,omitempty"`

	// TradeId Numerical identifier assigned by public authorities.
	TradeId *string `json:"tradeId,omitempty"`

	// Type Discriminator, set by agrirouter. Implied by the path on send.
	Type interface{} `json:"type,omitempty"`
}

// RevisionConflictError The `412` or `428` of a write: an `Error` carrying the revision the object is currently at, so that the client has the answer a rejected write would otherwise have to fetch separately.
type RevisionConflictError struct {
	// CurrentRevision The canonical object's current `revision`.
	CurrentRevision int    `json:"currentRevision"`
	Message         string `json:"message"`
}

// Role [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). A role drawn from the ADAPT Role data type.
//
// Examples: UNKNOWN, AUTHORIZER, CROP_ADVISOR, CUSTOMER, CUSTOM_SERVICE_PROVIDER, DATA_SERVICES_PROVIDER, END_USER, FARM_MANAGER, FINANCIER, STATIONARY_ASSET_SUPPLIER, GOVERNMENT_AGENCY, GROWER, INPUT_SUPPLIER, INSURANCE_AGENT, IRRIGATION_MANAGER, LABORER, MARKET_ADVISOR, MARKET_PROVIDER, MOBILE_ASSET_SUPPLIER, OPERATOR, OWNER, TRANSPORTER
type Role = string

// SoilInfo Soil characteristics of a field.
type SoilInfo struct {
	// RatingPoints Soil rating points (Bodenzahl / Ackerzahl). Germany only, as defined by the [Bodenschätzungsgesetz](https://www.bundesfinanzministerium.de/Content/DE/Standardartikel/Themen/Steuern/Weitere_Steuerthemen/2014-07-21-bodenschaetzung-anlage-VRBodSchaetzG.pdf?__blob=publicationFile&v=1).
	RatingPoints *int `json:"ratingPoints,omitempty"`

	// Type [Extensible enum](https://github.com/DKE-Data/masterdata-sync-working-group/blob/main/specification.md#extensible-enumerations). The soil classification.
	//
	//
	// Examples: SAND, LOAMY_SAND, HEAVY_LOAMY_SAND, SANDY_TO_SILTY_LOAM, CLAYEY_LOAM, CLAY
	Type *string `json:"type,omitempty"`
}

// AgrirouterEndpointId defines model for AgrirouterEndpointId.
type AgrirouterEndpointId = openapi_types.UUID

// BaseRevision defines model for BaseRevision.
type BaseRevision = int

// ExternalEndpointId defines model for ExternalEndpointId.
type ExternalEndpointId = string

// IdMappingAgrirouterId defines model for IdMappingAgrirouterId.
type IdMappingAgrirouterId = openapi_types.UUID

// LastEventId defines model for LastEventId.
type LastEventId = string

// LocalId defines model for LocalId.
type LocalId = string

// BaseRevisionRequired The `412` or `428` of a write: an `Error` carrying the revision the object is currently at, so that the client has the answer a rejected write would otherwise have to fetch separately.
type BaseRevisionRequired = RevisionConflictError

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InitialLoadConflict defines model for InitialLoadConflict.
type InitialLoadConflict = Error

// MappingConflict The `409` of a binding: an `Error` carrying the rejection that caused it. The same shape the bulk path returns per pair, so an endpoint resolves a conflict identically whichever path raised it. As there, the outcome is carried by `rejection.reason`; the `message` of the `Error` is diagnostic and MUST NOT be branched on.
type MappingConflict = MappingConflictError

// NotFound defines model for NotFound.
type NotFound = Error

// RevisionConflict The `412` or `428` of a write: an `Error` carrying the revision the object is currently at, so that the client has the answer a rejected write would otherwise have to fetch separately.
type RevisionConflict = RevisionConflictError

// ValidationError defines model for ValidationError.
type ValidationError = Error

// StreamMasterdataEventsParams defines parameters for StreamMasterdataEvents.
type StreamMasterdataEventsParams struct {
	// LastEventID The event id the application saved last from `/masterdata/events` stream, as agrirouter issued it in the `id:` field of an SSE frame. The application MUST send it back exactly as issued, treat it as an opaque string and MUST NOT interpret, compare, construct, or modify it in any way. Its structure is not defined by this API and may change; the example below illustrates its size and shape only.
	// It does not always advance on every frame: the same value may repeat on some frames, and an application MUST NOT read anything into that beyond its own position for `Last-Event-ID` being unchanged.
	//
	// The application MUST save it from what it has **durably applied** rather than from whatever its stream client last read; delivery is at-least-once, so everything after it is sent again on reconnect. Where applies complete out of order, store the id of the earliest frame, in the order the stream delivered them, that is not yet applied: ids are not comparable by the application, so this is a matter of remembering delivery order. It does not expire, and agrirouter stores no copy of it.
	//
	// Omitted, or present and one agrirouter cannot validate, is served as a first connection on this stream: everything the application is entitled to, ending with a `CAUGHT_UP` frame. That costs the application its place in the stream and not its entitlement, and is how it asks for every entity to be delivered again.
	//
	// This parameter applies to `/masterdata/events` only. The initial-load stream carries no position and does not accept it.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// RequestFarmParams defines parameters for RequestFarm.
type RequestFarmParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// PutFarmParams defines parameters for PutFarm.
type PutFarmParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// DeactivateFarmParams defines parameters for DeactivateFarm.
type DeactivateFarmParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// UnbindFarmMappingParams defines parameters for UnbindFarmMapping.
type UnbindFarmMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// BindFarmMappingParams defines parameters for BindFarmMapping.
type BindFarmMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// RequestFieldBoundaryParams defines parameters for RequestFieldBoundary.
type RequestFieldBoundaryParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// PutFieldBoundaryParams defines parameters for PutFieldBoundary.
type PutFieldBoundaryParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// DeactivateFieldBoundaryParams defines parameters for DeactivateFieldBoundary.
type DeactivateFieldBoundaryParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// UnbindFieldBoundaryMappingParams defines parameters for UnbindFieldBoundaryMapping.
type UnbindFieldBoundaryMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// BindFieldBoundaryMappingParams defines parameters for BindFieldBoundaryMapping.
type BindFieldBoundaryMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// RequestFieldParams defines parameters for RequestField.
type RequestFieldParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// PutFieldParams defines parameters for PutField.
type PutFieldParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// DeactivateFieldParams defines parameters for DeactivateField.
type DeactivateFieldParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// UnbindFieldMappingParams defines parameters for UnbindFieldMapping.
type UnbindFieldMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// BindFieldMappingParams defines parameters for BindFieldMapping.
type BindFieldMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// RequestOrganizationParams defines parameters for RequestOrganization.
type RequestOrganizationParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// PutOrganizationParams defines parameters for PutOrganization.
type PutOrganizationParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// DeactivateOrganizationParams defines parameters for DeactivateOrganization.
type DeactivateOrganizationParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// UnbindOrganizationMappingParams defines parameters for UnbindOrganizationMapping.
type UnbindOrganizationMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// BindOrganizationMappingParams defines parameters for BindOrganizationMapping.
type BindOrganizationMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// RequestPersonParams defines parameters for RequestPerson.
type RequestPersonParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// PutPersonParams defines parameters for PutPerson.
type PutPersonParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// DeactivatePersonParams defines parameters for DeactivatePerson.
type DeactivatePersonParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`

	// XAgrirouterBaseRevision The `revision` the client edited from — the base of this write. It is a precondition on the request, not part of the entity, which is why it travels as a header: `revision` in the body stays `readOnly` and server-assigned, and a client-supplied revision is compared, never assigned.
	//
	// Required on a write to an object that already exists; absent there is `428`, since omitting it would opt the client out of concurrency control. Absent on a create is normal, there being no base. Present on a request that does not resolve to an existing object it is `412`: the client believes it is updating something agrirouter does not know under that `localId`.
	//
	// A base behind the current revision is not necessarily a failure. agrirouter three-way merges where the client's change and the intervening ones do not overlap and answers `200` with the merged object, whose `revision` is then not base + 1; where they overlap it answers `412` with the current revision. A write whose payload equals the current canonical value succeeds as a no-op whatever the base. See "Concurrency control" in specification.md.
	XAgrirouterBaseRevision *BaseRevision `json:"x-agrirouter-base-revision,omitempty"`
}

// UnbindPersonMappingParams defines parameters for UnbindPersonMapping.
type UnbindPersonMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// BindPersonMappingParams defines parameters for BindPersonMapping.
type BindPersonMappingParams struct {
	// XAgrirouterEndpointId The endpoint acting — the sender of an entity, the caller of a request, the holder of a binding. The token authorizes an *application*, which holds many endpoints across many tenants, so the acting one is named per request rather than derived. It decides entitlement and the tenant, and it becomes the `sourceEndpointId` of any revision produced. It does not scope `localId`, which resolves in the application's namespace.
	//
	// This is the agrirouter endpoint ID — the `id` of the endpoint, not the `external_id` the application chose for it. An application already holds it: it is returned when the endpoint is created or updated, listed with the tenant's endpoints, and carried on the endpoint events. The same header identifies the sending endpoint on every master-data write.
	XAgrirouterEndpointId AgrirouterEndpointId `json:"x-agrirouter-endpoint-id"`
}

// SetInitialLoadStateJSONRequestBody defines body for SetInitialLoadState for application/json ContentType.
type SetInitialLoadStateJSONRequestBody = InitialLoadStateUpdate

// RequestFarmJSONRequestBody defines body for RequestFarm for application/json ContentType.
type RequestFarmJSONRequestBody = EntityRequest

// PutFarmJSONRequestBody defines body for PutFarm for application/json ContentType.
type PutFarmJSONRequestBody = Farm

// RequestFieldBoundaryJSONRequestBody defines body for RequestFieldBoundary for application/json ContentType.
type RequestFieldBoundaryJSONRequestBody = EntityRequest

// PutFieldBoundaryJSONRequestBody defines body for PutFieldBoundary for application/json ContentType.
type PutFieldBoundaryJSONRequestBody = FieldBoundary

// RequestFieldJSONRequestBody defines body for RequestField for application/json ContentType.
type RequestFieldJSONRequestBody = EntityRequest

// PutFieldJSONRequestBody defines body for PutField for application/json ContentType.
type PutFieldJSONRequestBody = Field

// RequestOrganizationJSONRequestBody defines body for RequestOrganization for application/json ContentType.
type RequestOrganizationJSONRequestBody = EntityRequest

// PutOrganizationJSONRequestBody defines body for PutOrganization for application/json ContentType.
type PutOrganizationJSONRequestBody = Organization

// RequestPersonJSONRequestBody defines body for RequestPerson for application/json ContentType.
type RequestPersonJSONRequestBody = EntityRequest

// PutPersonJSONRequestBody defines body for PutPerson for application/json ContentType.
type PutPersonJSONRequestBody = Person

// AsOrganization returns the union data inside the Entity as a Organization
func (t Entity) AsOrganization() (Organization, error) {
	var body Organization
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOrganization overwrites any union data inside the Entity as the provided Organization
func (t *Entity) FromOrganization(v Organization) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"organization"}`))
	t.union = b
	return err
}

// MergeOrganization performs a merge with any union data inside the Entity, using the provided Organization
func (t *Entity) MergeOrganization(v Organization) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"organization"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPerson returns the union data inside the Entity as a Person
func (t Entity) AsPerson() (Person, error) {
	var body Person
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPerson overwrites any union data inside the Entity as the provided Person
func (t *Entity) FromPerson(v Person) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"person"}`))
	t.union = b
	return err
}

// MergePerson performs a merge with any union data inside the Entity, using the provided Person
func (t *Entity) MergePerson(v Person) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"person"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFarm returns the union data inside the Entity as a Farm
func (t Entity) AsFarm() (Farm, error) {
	var body Farm
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFarm overwrites any union data inside the Entity as the provided Farm
func (t *Entity) FromFarm(v Farm) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"farm"}`))
	t.union = b
	return err
}

// MergeFarm performs a merge with any union data inside the Entity, using the provided Farm
func (t *Entity) MergeFarm(v Farm) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"farm"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsField returns the union data inside the Entity as a Field
func (t Entity) AsField() (Field, error) {
	var body Field
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromField overwrites any union data inside the Entity as the provided Field
func (t *Entity) FromField(v Field) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"field"}`))
	t.union = b
	return err
}

// MergeField performs a merge with any union data inside the Entity, using the provided Field
func (t *Entity) MergeField(v Field) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"field"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFieldBoundary returns the union data inside the Entity as a FieldBoundary
func (t Entity) AsFieldBoundary() (FieldBoundary, error) {
	var body FieldBoundary
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFieldBoundary overwrites any union data inside the Entity as the provided FieldBoundary
func (t *Entity) FromFieldBoundary(v FieldBoundary) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"fieldBoundary"}`))
	t.union = b
	return err
}

// MergeFieldBoundary performs a merge with any union data inside the Entity, using the provided FieldBoundary
func (t *Entity) MergeFieldBoundary(v FieldBoundary) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b, err = runtime.JSONMerge(b, []byte(`{"type":"fieldBoundary"}`))
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Entity) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Entity) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "farm":
		return t.AsFarm()
	case "field":
		return t.AsField()
	case "fieldBoundary":
		return t.AsFieldBoundary()
	case "organization":
		return t.AsOrganization()
	case "person":
		return t.AsPerson()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Entity) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Entity) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsEntityReference0 returns the union data inside the EntityReference as a EntityReference0
func (t EntityReference) AsEntityReference0() (EntityReference0, error) {
	var body EntityReference0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEntityReference0 overwrites any union data inside the EntityReference as the provided EntityReference0
func (t *EntityReference) FromEntityReference0(v EntityReference0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEntityReference0 performs a merge with any union data inside the EntityReference, using the provided EntityReference0
func (t *EntityReference) MergeEntityReference0(v EntityReference0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEntityReference1 returns the union data inside the EntityReference as a EntityReference1
func (t EntityReference) AsEntityReference1() (EntityReference1, error) {
	var body EntityReference1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEntityReference1 overwrites any union data inside the EntityReference as the provided EntityReference1
func (t *EntityReference) FromEntityReference1(v EntityReference1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEntityReference1 performs a merge with any union data inside the EntityReference, using the provided EntityReference1
func (t *EntityReference) MergeEntityReference1(v EntityReference1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EntityReference) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AgrirouterId != nil {
		object["agrirouterId"], err = json.Marshal(t.AgrirouterId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'agrirouterId': %w", err)
		}
	}

	if t.LocalId != nil {
		object["localId"], err = json.Marshal(t.LocalId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'localId': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *EntityReference) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["agrirouterId"]; found {
		err = json.Unmarshal(raw, &t.AgrirouterId)
		if err != nil {
			return fmt.Errorf("error reading 'agrirouterId': %w", err)
		}
	}

	if raw, found := object["localId"]; found {
		err = json.Unmarshal(raw, &t.LocalId)
		if err != nil {
			return fmt.Errorf("error reading 'localId': %w", err)
		}
	}

	return err
}

// AsPartyReference0 returns the union data inside the PartyReference as a PartyReference0
func (t PartyReference) AsPartyReference0() (PartyReference0, error) {
	var body PartyReference0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPartyReference0 overwrites any union data inside the PartyReference as the provided PartyReference0
func (t *PartyReference) FromPartyReference0(v PartyReference0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePartyReference0 performs a merge with any union data inside the PartyReference, using the provided PartyReference0
func (t *PartyReference) MergePartyReference0(v PartyReference0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPartyReference1 returns the union data inside the PartyReference as a PartyReference1
func (t PartyReference) AsPartyReference1() (PartyReference1, error) {
	var body PartyReference1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPartyReference1 overwrites any union data inside the PartyReference as the provided PartyReference1
func (t *PartyReference) FromPartyReference1(v PartyReference1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePartyReference1 performs a merge with any union data inside the PartyReference, using the provided PartyReference1
func (t *PartyReference) MergePartyReference1(v PartyReference1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PartyReference) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AgrirouterId != nil {
		object["agrirouterId"], err = json.Marshal(t.AgrirouterId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'agrirouterId': %w", err)
		}
	}

	if t.LocalId != nil {
		object["localId"], err = json.Marshal(t.LocalId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'localId': %w", err)
		}
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *PartyReference) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["agrirouterId"]; found {
		err = json.Unmarshal(raw, &t.AgrirouterId)
		if err != nil {
			return fmt.Errorf("error reading 'agrirouterId': %w", err)
		}
	}

	if raw, found := object["localId"]; found {
		err = json.Unmarshal(raw, &t.LocalId)
		if err != nil {
			return fmt.Errorf("error reading 'localId': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}
